version: '3.8'

services:
  app:
    build: .  # Backend
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://Retailflow:3306/inventario
      DB_USERNAME: root
      DB_PASSWORD: password
    restart: always
    depends_on:
      Retailflow:
        condition: service_healthy

  Retailflow:
    image: mysql:8.0.41
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: inventario
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  frontend:
    build:
      context: ../FrontendRetailFlow-main  # 📌 Ruta al frontend
    ports:
      - "5173:5174"  # 📌 Exponer Vite en http://localhost:5173
    volumes:
      - ../FrontendRetailFlow-main:/app  # Permitir live reload
      - /app/node_modules  # Evitar problemas con node_modules
    command: ["npm", "run", "dev", "--", "--host"]
    environment:
      - CHOKIDAR_USEPOLLING=true  # Hot reload en Windows

