name: Maven Build, Test, and Docker Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Build and run tests
        run: mvn clean install

      - name: Log in to Docker Hub
        run: echo dckr_pat_hS0f1aMwMm87VNkY841Qoeja00w | docker login -u joang1 --password-stdi

      - name: Build Docker image
        run: docker build -t joang1/ideaprojects-backend:latest .

      - name: Push Docker image
        run: docker push joang1/ideaprojects-backend:latest
